name: nd2venv
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.6.0=hd77b12b_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - blosc=1.21.3=h6c2663c_0
  - brotli=1.0.9=h2bbff1b_8
  - brotli-bin=1.0.9=h2bbff1b_8
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2024.9.24=haa95532_0
  - cfitsio=3.470=h2bbff1b_7
  - charls=2.2.0=h6c2663c_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.0=py312h59b6b97_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.8.7=py312h275cf98_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.6.3=he0c23c2_0
  - fonttools=4.51.0=py312h2bbff1b_0
  - freetype=2.12.1=ha860e81_0
  - giflib=5.2.2=h7edc060_0
  - imagecodecs=2023.1.23=py312hd5bf116_1
  - importlib-metadata=8.5.0=pyha770c72_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.29.0=pyh7428d3b_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=py312haa95532_0
  - jpeg=9e=h827c3e9_3
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py312h2e8e312_0
  - kiwisolver=1.4.4=py312hd77b12b_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libaec=1.0.4=h33f27b4_1
  - libavif=0.11.1=h2bbff1b_0
  - libbrotlicommon=1.0.9=h2bbff1b_8
  - libbrotlidec=1.0.9=h2bbff1b_8
  - libbrotlienc=1.0.9=h2bbff1b_8
  - libdeflate=1.17=h2bbff1b_1
  - libexpat=2.6.3=he0c23c2_0
  - libffi=3.4.4=hd77b12b_1
  - libpng=1.6.39=h8cc25b3_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.47.0=h2466b09_0
  - libtiff=4.5.1=hd77b12b_0
  - libwebp-base=1.3.2=h3d04722_1
  - libzlib=1.2.13=h2466b09_6
  - libzopfli=1.0.3=ha925a31_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=2.1.3=py312h2bbff1b_0
  - matplotlib-base=3.9.2=py312hbdc63d0_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py312h2bbff1b_1
  - mkl_fft=1.3.10=py312h827c3e9_0
  - mkl_random=1.2.7=py312h0158946_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - numpy=1.26.4=py312hfd52020_0
  - numpy-base=1.26.4=py312h4dde369_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.3.2=h2466b09_0
  - packaging=24.1=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py312h827c3e9_0
  - pip=24.2=pyh8b19718_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - psutil=6.1.0=py312h4389bb4_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.1.2=py312haa95532_0
  - python=3.12.3=h2628c8c_0_cpython
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python_abi=3.12=5_cp312
  - pywin32=307=py312h275cf98_3
  - pyzmq=26.2.0=py312hd7027bb_3
  - setuptools=75.1.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - slicerator=1.1.0=py312haa95532_0
  - snappy=1.2.1=hcdb6601_0
  - sqlite=3.47.0=h2466b09_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.14=h0416ee5_0
  - tornado=6.4.1=py312h4389bb4_1
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024b=hc8b5060_0
  - ucrt=10.0.22621.0=h57928b3_1
  - unicodedata2=15.1.0=py312h2bbff1b_0
  - vc=14.40=h2eaa2aa_1
  - vc14_runtime=14.40.33810=hcc2c482_22
  - vs2015_runtime=14.40.33810=h3bf8584_22
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - xz=5.4.6=h8cc25b3_1
  - zeromq=4.3.5=ha9f60a1_6
  - zfp=1.0.0=hd77b12b_0
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.2.13=h2466b09_6
  - zstd=1.5.6=h8880b57_0
  - pip:
      - arrow==1.3.0
      - attrs==24.2.0
      - fastjsonschema==2.20.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - imageio==2.36.0
      - import-ipynb==0.2
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - nbformat==5.10.4
      - nd2reader==3.3.0
      - pexpect==4.9.0
      - pims==0.7
      - ptyprocess==0.7.0
      - referencing==0.35.1
      - rpds-py==0.20.0
      - smmap==5.0.1
      - tifffile==2024.9.20
      - types-python-dateutil==2.9.0.20241003
      - xmltodict==0.14.2
